### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by cdeclerck** [BitBagCommerce/SyliusVueStorefront2Plugin#40]
Hello,

I try to install this plugin. However when I want to start my sylius I have an error when I run the "cache:clear" command:
`Script cache:clear returned with error code 1
!!  
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
!!                                                                                 
!!    The service "Sylius\Bundle\ApiBundle\CommandHandler\Checkout\ChoosePaymentM  
!!    ethodHandler" has a dependency on a non-existent service "Sylius\Bundle\Api  
!!    Bundle\Changer\PaymentMethodChanger". Did you mean this: "Sylius\Bundle\Api  
!!    Bundle\Changer\PaymentMethodChangerInterface"?                               
!!                                                                                 
!!  
!!`

 do you have an idea ? problem with sylius ? with the integration of the plugin ?

**Comment by niic0** [comment]
Hello, same problem here... I'm stuck on this problem since days, did you find any solution ?

**Comment by perfectglitch** [comment]
Also service references 'sylius.api.context.user' seems to be renamed to 'Sylius\Bundle\ApiBundle\Context\UserContextInterface' since Sylius 1.11. The upgrade notes are present in the Sylius composer package though I can't find then in this repo or official site.

**Comment by PiotrSzymanski2000** [comment]
Corrections have been made
