### ISSUE TITLE
Is this project still in Beta?

### ISSUE THREAD

**Issue by spyesx** [BitBagCommerce/SyliusVueStorefront2Plugin#69]
Hi,

This project is tagged as `BETA` on [VSF's integrations page](https://docs.vuestorefront.io/v2/integrations/#ecommerce-platforms). However I see no beta mention in this repo.

Is it ready for production?

**Comment by rafalmal** [comment]
We will update plugin to sylius 1.12 soon.

**Comment by senghe** [comment]
@spyesx thanks for issue you open. No, it's no longer beta. I've asked the VSF team to remove the badge and it looks it's removed from now.
And yes, our integration is ready for production use.
